baseurl               = "http://html5nagoya.jp/"
languageCode          = "ja-jp"
title                 = "HTML5NAGOYA"
theme                 = "html5nagoya"
hasCJKLanguage        = true
Paginate              = 100
preserveTaxonomyNames = true
ignoreFiles           = []
EnableGitInfo         = true

[params]
author      = "html5nagoya"
description = "HTML5NAGOYA は HTML / CSS / JavaScript を始めとした Web のフロントエンドの技術全般を学び合う勉強会です。 "

[permalinks]
post = "/post/:slug/"

[blackfriday]
fractions       = false
hrefTargetBlank = true
plainIDAnchors  = true
